services:
  ossfs:
    image: ntlv1/ossfs:1.91.1
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - OSS_URL=${OSS_URL}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - ACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - MNT_POINT=/data/ossfs
    volumes:
      - ${MNT_DIR:-/mnt/docker}/${OSSFS_DIR:-ossfs_mysqldump}:/data/ossfs:rshared

  mysql-client: 
    image: arey/mysql-client
    restart: unless-stopped
    volumes:
      - ${TMP_DIR:-/tmp/mysql-client}:/tmp
      - ${MNT_DIR:-/mnt/docker}/${OSSFS_DIR:-ossfs_mysqldump}:/ossfs
    entrypoint: ["/bin/ash", "-c"]
    command:
      - |
        while true; do
          echo $(date +'%H:%M')
          if [ "$(date +'%H:%M')" = '${EXEC_TIME1}' ]; then
            ./ossfs/run.sh
          elif [ "$(date +'%H:%M')" = '${EXEC_TIME2}' ]; then
            ./ossfs/run.sh
          fi
          sleep 60
        done
    depends_on:
      - ossfs
