services:
  ossfs:
    image: ntlv1/ossfs:1.91.1
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - OSS_URL=${OSS_URL}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - ACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - MNT_POINT=/data/ossfs
    volumes:
      - ${MNT_DIR:-/mnt/docker}/ossfs_mysqldump:/data/ossfs:rshared
    networks:
      - others

  mysql-client:
    image: arey/mysql-client
    restart: unless-stopped
    volumes:
      - ${MNT_DIR:-/mnt/docker}/ossfs_mysqldump:/ossfs 
      - ${TMP_DIR:-/tmp/mysql-client}:/tmp 
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
    entrypoint: ["/bin/ash", "-c"]
    command:
      - |
        while true; do
          current_time=$(date +'%H:%M')
          echo $(date +'%H:%M')
          IFS=','
          set -- $${EXEC_TIME}
          for exec_time in "$$@"; do
            if [ "$$current_time" = "$$exec_time" ]; then
              ./ossfs/run.sh
              break
            fi
          done
          sleep 60
        done
    environment:
      - EXEC_TIME=${EXEC_TIME:-15:05,05:05}
    depends_on:
      - ossfs
    networks:
      - others

networks:
  others:
    external: true
