services:
  logger:
    image: umputun/docker-logger
    restart: always

    environment:
      LOG_FILES: ${LOG_FILES:-true}
      MAX_SIZE: ${MAX_SIZE:-10}
      MAX_FILES: ${MAX_FILES:-10}
      MAX_AGE: ${MAX_AGE:-30}
      INCLUDE: ${INCLUDE}
      TIME_ZONE: ${TZ:-Asia/Shanghai}
      JSON: ${JSON:-true}
      DEBUG: ${DEBUG:-false}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - docker-logger:/srv/logs
      - /var/run/docker.sock:/var/run/docker.sock

    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  docker-logger:
