services:
  logger:
    image: umputun/docker-logger
    restart: always
    environment:
      - LOG_FILES=true
      - MAX_FILES=10
      - MAX_SIZE=1
      - MAX_AGE=7
      - DEBUG=false
      - TIME_ZONE=${TZ:-Asia/Shanghai}
      - INCLUDE=${INCLUDE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MNT_DIR:-/mnt/docker}/docker-logger:/srv/logs
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
