services:
  wallos:
    image: bellamy/wallos:${IMAGE_TAG:-latest}
    container_name: ${NAME:-wallos}
    restart: always
    ports:
      - ${PORT:-8282}:80
    environment:
      - TZ=${GENERIC_TIMEZONE:-Asia/Shanghai}
    volumes:
      - ${MNT_DIR:-/mnt/docker}/wallos/db:/var/www/html/db
      - ${MNT_DIR:-/mnt/docker}/wallos/logos:/var/www/html/images/uploads/logos
    labels:
      # traefik
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.docker.network=${TRAEFIK_DOCKER_NETWORK:-web}
      - traefik.http.routers.${NAME:-wallos}.rule=Host(`${HOST:-wallos.localhost}`)
      - traefik.http.services.${NAME:-wallos}.loadbalancer.server.port=80
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}
