services:
  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/ash", "-c"]
    command:
      - |
        while true; do
          current_time=$(date +'%H:%M')
          echo $(date +'%H:%M')
          IFS=','; set -- $${EXEC_TIMES}

          for exec_time in "$$@"; do
            if [ "$$current_time" = "$$exec_time" ]; then
              echo $(date +'%H:%M')
              IFS=','; set -- $${CONTAINERS}

              for container in "$$@"; do
                # 检查容器是否存在
                if docker ps -a | grep -q "$${container}"; then
                  docker restart "$${container}" && \
                    echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Successfully restarted: $${container}" >> /tmp/restart.log
                else
                  echo "[$$(date +'%Y-%m-%d %H:%M:%S')] ERROR: Container $${container} does not exist!" >> /tmp/restart.log
                fi
              done

              echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Triggered at: $$current_time" >> /tmp/restart.log
              break 
            fi
          done
          sleep 60
        done
    environment:
      - EXEC_TIMES=${EXEC_TIMES}
      - CONTAINERS=${CONTAINERS}
