services:
  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/ash", "-c"]
    command:
      - |
        while true; do
          current_time=$$(date +'%H:%M')
          IFS=';'
          for group in $${CONTAINERS_EXEC_TIME}; do
              IFS=':' read -r container_name times_part <<EOF
        $$group
        EOF
              IFS=','; set -- $$times_part
              for exec_time in "$$@"; do
                  if [ "$$current_time" = "$$exec_time" ]; then
                      if docker inspect "$${container_name}" >/dev/null 2>&1; then
                          docker restart "$${container_name}" && \
                            echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Successfully restarted: $${container_name}" >> /tmp/restart.log
                      else
                          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] ERROR: Container $${container_name} does not exist!" >> /tmp/restart.log
                      fi
                      echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Triggered at: $$current_time for $${container_name}" >> /tmp/restart.log
                      break
                  fi
              done
          done
          sleep 60
        done
    environment:
      - CONTAINERS_EXEC_TIME=${CONTAINERS_EXEC_TIME}
