services:
  clash:
    image: dreamacro/clash:v1.18.0
    container_name: clash
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MNT_DIR}/clash/config.yaml:/root/.config/clash/config.yaml:ro
    ports:
      - '7890:7890/tcp'
      - '7890:7890/udp'
      - '9090:9090'
