services:
  bifrost:
    image: maximhq/bifrost:${BIFROST_IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-bifrost}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT:-8080}:8080"

    extra_hosts:
      - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "/dev/null", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    volumes:
      - ${MNT_DIR:-/mnt/docker}/bifrost:/app/data
