version: "3.8"
services:
  recorder:
    image: bililive/recorder:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${MNT_DIR}/bililive
        target: /rec
    ports:
      - "2356:2356"
    environment:
      - BREC_HTTP_BASIC_USER=${BREC_HTTP_BASIC_USER}
      - BREC_HTTP_BASIC_PASS=${BREC_HTTP_BASIC_PASS}