services:
  rsshub:
    image: diygod/rsshub:${RSSHUB_IMAGE_TAG:-chromium-bundled}
    # container_name: ${RSSHUB_CONTAINER_NAME:-rsshub}

    restart: unless-stopped

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - db_network
    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${RSSHUB_HOST_PORT:-1200}:1200"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      CACHE_TYPE: ${CACHE_TYPE:-redis}
      NODE_ENV: production
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/}

    labels:
      com.centurylinklabs.watchtower.enable: ${RSSHUB_WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:${REDIS_IMAGE_TAG:-7.4.8-alpine}
    # container_name: ${REDIS_CONTAINER_NAME:-redis}

    restart: unless-stopped

    networks:
      - db_network
    # extra_hosts:
    #   - host.docker.internal:host-gateway

    labels:
      com.centurylinklabs.watchtower.enable: ${REDIS_WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

    volumes:
      - redis-data:/data

networks:
  db_network:

volumes:
  redis-data:
    name: ${REDIS_VOLUME_NAME:-rsshub-redis-data}
