services:
  rsshub:
    image: diygod/rsshub:${IMAGE_TAG:-chromium-bundled}
    restart: always
    ports:
      - ${PORT:-1200}:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    labels:
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}
    networks:
      - db_network
      - web
    depends_on:
      - redis

  redis:
    image: redis:${REDIS_IMAGE_TAG:-alpine}
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - db_network
    labels:
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}

volumes:
  redis-data:

networks:
  db_network:
  web:
    external: true
