services:
  rsshub:
    image: diygod/rsshub:${IMAGE_TAG:-chromium-bundled}
    restart: always
    ports:
      - ${PORT:-1200}:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    depends_on:
      - redis

  redis:
    image: redis:${REDIS_IMAGE_TAG:-alpine}
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
