services:
  nga-post-archive:
    image: sliots/nga-post-archive:${IMAGE_TAG:-latest}
    # container_name: ${CONTAINER_NAME:-nga-post-archive}

    restart: unless-stopped

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      RUN_CRON: "0 3 * * *"
      RUN_AT_START: ${RUN_AT_START:-true}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/nga-post-archive:/app/data
