services:
  server:
    image: docker.gitea.com/gitea:${GITEA_IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-gitea}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${GITEA_PORT:-3000}:3000"
      - "${BIND_ADDRESS:-0.0.0.0}:${GITEA_SSH_PORT:-222}:22"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      GITEA__server__SSH_PORT: ${GITEA_SSH_PORT:-222}
    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
