services:
  db:
    image: postgres:18
    restart: unless-stopped

    ports:
      - ${DB_PORT:-5432}:5432

    environment:
      POSTGRES_USER: ${TTRSS_DB_USER}
      POSTGRES_PASSWORD: ${TTRSS_DB_PASS}
      POSTGRES_DB: ${TTRSS_DB_NAME}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/ttrss/db:/var/lib/postgresql
      - /tmp:/tmp

  app:
    image: supahgreg/tt-rss:latest
    restart: unless-stopped

    depends_on:
      - db

    environment:
      SKIP_RSYNC_ON_STARTUP: true
      ADMIN_USER_PASS: ${ADMIN_USER_PASS}
      ADMIN_USER_ACCESS_LEVEL: ${ADMIN_USER_ACCESS_LEVEL:-10}
      TTRSS_DB_USER: ${TTRSS_DB_USER:-postgres}
      TTRSS_DB_NAME: ${TTRSS_DB_NAME:-postgres}
      TTRSS_DB_PASS: ${TTRSS_DB_PASS}
      TTRSS_SESSION_COOKIE_LIFETIME: ${TTRSS_SESSION_COOKIE_LIFETIME:-2592000}
      TTRSS_SELF_URL_PATH: ${TTRSS_SELF_URL_PATH}
      HTTP_PORT: ${HTTP_PORT}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/ttrss/app:/var/www/html/tt-rss

  updater:
    image: supahgreg/tt-rss:latest
    restart: unless-stopped
    command: /opt/tt-rss/updater.sh

    depends_on:
      - app

    environment:
      TTRSS_DB_USER: ${TTRSS_DB_USER:-postgres}
      TTRSS_DB_NAME: ${TTRSS_DB_NAME:-postgres}
      TTRSS_DB_PASS: ${TTRSS_DB_PASS}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/ttrss/app:/var/www/html/tt-rss

  web-nginx:
    image: supahgreg/tt-rss-web-nginx:latest
    restart: unless-stopped

    depends_on:
      - app

    ports:
      - ${HTTP_PORT}:80

    volumes:
      - ${MNT_DIR:-/mnt/docker}/ttrss/app:/var/www/html/tt-rss:ro
