services:
  recorder:
    image: bililive/recorder:${IMAGE_TAG:-2}
    restart: unless-stopped

    ports:
      - ${PORT:-2356}:2356

    environment:
      BREC_HTTP_BASIC_USER: ${BREC_HTTP_BASIC_USER}
      BREC_HTTP_BASIC_PASS: ${BREC_HTTP_BASIC_PASS}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/bililive:/rec

    extra_hosts:
      - host.docker.internal:host-gateway
