services:
  recorder:
    image: bililive/recorder:${IMAGE_TAG:-2}
    # container_name: ${CONTAINER_NAME:-recorder}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT:-2356}:2356"

    extra_hosts:
      - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/bililive:/rec
