services:
  traefik:
    container_name: traefik
    image: traefik:${IMAGE_TAG:-v3.2}
    restart: always
    ports:
      - ${PORT_WEB:-80}:80
      - ${PORT_DASHBOARD:-8080}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--log.level=${LOG_LEVEL}"
      - "--api.dashboard=${API_DASHBOARD:-true}"
      - "--api.insecure=${API_INSECURE:-true}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entryPoints.web.address=:80"
    networks:
      - web
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}

networks:
  web:
    external: true
