services:
  neko-master:
    image: foru17/neko-master:latest
    container_name: ${CONTAINER_NAME:-neko-master}
    restart: unless-stopped

    ports:
      - ${PORT:-3000}:3000

    environment:
      NODE_ENV: production
      DB_PATH: /app/data/stats.db
      COOKIE_SECRET: ${COOKIE_SECRET}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/neko-master/data:/app/data
      # Local MMDB (optional, files should be downloaded into ./geoip)
      - ${MNT_DIR:-/mnt/docker}/neko-master/geoip:/app/data/geoip:ro

    extra_hosts:
      - host.docker.internal:host-gateway
