services:
  super-image:
    image: tucangcc/super-image:${IMAGE_TAG:-latest}
    # container_name: ${SUPER_IMAGE_CONTAINER_NAME:-super-image}

    restart: always

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT}:80"

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CLASSFINAL_PASSWORD: ${CLASSFINAL_PASSWORD:?CLASSFINAL_PASSWORD is required}
      JAVA_OPTS: >-
        -Xms512m -Xmx512m -Duser.timezone=${TZ:-Asia/Shanghai}
        -Xloggc:/logs/gc.log -XX:+PrintGC -XX:+PrintGCDetails
        -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError
        -XX:-OmitStackTraceInFastThrow -XX:+UseG1GC

    labels:
      com.centurylinklabs.watchtower.enable: ${SUPER_IMAGE_WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/tucang-customized/config:/app/config
      - ${MNT_DIR:-/mnt/docker}/tucang-customized/images:/app/images
      - ${MNT_DIR:-/mnt/docker}/tucang-customized/logs:/app/logs

  valkey:
    image: valkey/valkey:${VALKEY_IMAGE_TAG:-9}
    # container_name: ${VALKEY_CONTAINER_NAME:-valkey}

    restart: always

    command: >
      valkey-server
      --requirepass ${VALKEY_PASS}
      --save 60 1
      --appendonly no
    # extra_hosts:
    #   - host.docker.internal:host-gateway

    labels:
      com.centurylinklabs.watchtower.enable: ${VALKEY_WATCHTOWER_ENABLE:-true}
