services:
  onenav:
    image: helloz/onenav:${IMAGE_TAG:-latest}
    container_name: onenav
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - ${MNT_DIR:-/mnt/docker}/onenav/data:/data/wwwroot/default/data
    labels:
      # traefik
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.onenav.rule=Host(`${HOST:-onenav.localhost}`)
      - traefik.http.services.onenav.loadbalancer.server.port=80
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}

networks:
  web:
    external: true
