services:
  rabbitmq:
    image: rabbitmq:${IMAGE_TAG:-3.13.7-alpine}
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      - ${PORT:-5672}:5672

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
