services:
  view:
    image: tucangcc/tucang-view-sync:${IMAGE_TAG:-latest}
    # container_name: ${CONTAINER_NAME:-view}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT}:80"

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+UseG1GC"

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/tucang/config:/config

    tmpfs:
      - /logs

    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-800m}
