services:
  view:
    image: tucangcc/tucang-view-sync:${IMAGE_TAG:-latest}
    restart: unless-stopped

    ports:
      - ${PORT}:80

    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+UseG1GC"

    volumes:
      - ${MNT_DIR:-/mnt/docker}/tucang/config:/config

    tmpfs:
      - /logs

    logging:
      driver: json-file
      options:
        max-size: 0.1g
        max-file: "1"

    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-800m}
