services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:${IMAGE_TAG:-latest}

    restart: unless-stopped

    ports:
      - ${BACKREST_HOST_PORT:-9898}:9898

    extra_hosts:
      - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false

    environment:
      TZ: ${TZ:-Asia/Shanghai}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9898"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    volumes:
      - ${MNT_DIR}data:/data
      - ${MNT_DIR}config:/config
      - ${MNT_DIR}cache:/cache
      - ${MNT_DIR}tmp:/tmp
      # - ${MNT_DIR}rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      # - ${MNT_DIR}repos:/repos # Mount local repos (optional for remote storage)
      - ${USERDATA_DIR}:/userdata:ro

volumes:
  data:
  config:
  cache:
  tmp:
  rclone:
  repos:
