services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-backrest}
    hostname: ${BACKREST_HOSTNAME:-backrest}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT:-9898}:9898"

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
      TMPDIR: /tmp

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9898"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    volumes:
      - ${MNT_DIR:-/mnt/docker}/backrest/data:/data
      - ${MNT_DIR:-/mnt/docker}/backrest/config:/config
      - ${MNT_DIR:-/mnt/docker}/backrest/cache:/cache
      - ${MNT_DIR:-/mnt/docker}/backrest/tmp:/tmp
      - ${MNT_DIR:-/mnt/docker}/backrest/rclone:/root/.config/rclone
      - ${USERDATA_DIR:-/mnt/docker}:/userdata:ro
      # 使用本地 restic 仓库时取消注释，该目录需要写权限。
      # - ${REPOS_DIR:-/mnt/docker/backrest/repos}:/repos
