services:
  app:
    image: cooderl/wewe-rss-sqlite:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      # 数据库连接地址
      - DATABASE_URL=file:../data/wewe-rss.db
      - DATABASE_TYPE=sqlite
      # 服务接口请求授权码
      - AUTH_CODE=${AUTH_CODE}
      # 提取全文内容模式
      - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=${CRON_EXPRESSION}
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=${MAX_REQUEST_PER_MINUTE}
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=${SERVER_ORIGIN_URL}

    volumes:
      # 映射数据库文件存储位置，容器重启后不丢失
      - ${MNT_DIR}/wewe-rss:/app/data