services:
  typesense:
    image: typesense/typesense:${IMAGE_TAG:-latest}
    container_name: typesense
    restart: always
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    ports:
      - ${PORT:-8108}:8108
    labels:
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}
    networks:
      - web

volumes:
  typesense-data:

networks:
  web:
    external: true
