services:
  qd:
    image: qdtoday/qd:${IMAGE_TAG:-latest}
    restart: always

    depends_on:
      - valkey

    networks:
      - qd

    ports:
      - ${PORT}:80

    environment:
      COOKIE_SECRET: ${COOKIE_SECRET}
      PBKDF2_ITERATIONS: ${PBKDF2_ITERATIONS:-400}
      AES_KEY: ${AES_KEY}
      REDISCLOUD_URL: "redis://valkey:6379"
      PROXIES: ${PROXIES}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/qd/database.db:/usr/src/app/config/database.db

    extra_hosts:
      - host.docker.internal:host-gateway

  valkey:
    image: valkey/valkey:${VALKEY_IMAGE_TAG:-9}
    restart: always

    networks:
      - qd

    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  qd:
