services:
  qd:
    image: qdtoday/qd:${IMAGE_TAG:-latest}
    container_name: qd
    restart: always

    depends_on:
      - valkey

    networks:
      - qd

    ports:
      - ${PORT}:80

    environment:
      COOKIE_SECRET: ${COOKIE_SECRET}
      PBKDF2_ITERATIONS: ${PBKDF2_ITERATIONS:-400}
      AES_KEY: ${AES_KEY}
      REDISCLOUD_URL: "redis://valkey:6379"
      PROXIES: "${PROXIES:-['http://host.docker.internal:7890']}"

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/qd/config:/usr/src/app/config

    extra_hosts:
      - host.docker.internal:host-gateway

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

  valkey:
    image: valkey/valkey:${VALKEY_IMAGE_TAG:-9}
    restart: always

    networks:
      - qd

    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  qd:
