services:
  qd:
    image: qdtoday/qd:${IMAGE_TAG:-latest}
    container_name: qd
    restart: always
    depends_on:
      - redis
    ports:
      - ${PORT}:80
    volumes:
      - ${MNT_DIR:-/mnt/docker}/qd/config:/usr/src/app/config
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PBKDF2_ITERATIONS=${PBKDF2_ITERATIONS:-400}
      - AES_KEY=${AES_KEY}
      - REDISCLOUD_URL=redis://redis:6379
      - PROXIES=${PROXIES:-['http://172.17.0.1:7890']}
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true} # watchtower
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    networks:
      - qd
      - web

  redis:
    image: bitnami/redis:${REDIS_IMAGE_TAG:-7}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true} # watchtower
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    networks:
      - qd

networks:
  qd:
  web:
    external: true
