services:
  derper:
    image: fredliang/derper
    container_name: derper
    restart: unless-stopped
    ports:
      - ${DERP_PORT}:443
      - ${STUN_PORT}:3478/udp
    environment:
      - DERP_DOMAIN=${DERP_DOMAIN}
      - DERP_CERT_MODE=manual
      - DERP_CERT_DIR=/app/certs
      - DERP_VERIFY_CLIENTS=true
      - DERP_HTTP_PORT=-1
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ${CRT_DIR}:/app/certs/${DERP_DOMAIN}.crt
      - ${KEY_DIR}:/app/certs/${DERP_DOMAIN}.key
