services:
  mcl:
    image: kagurazakanyaa/mcl:${IMAGE_TAG:-latest}
    restart: unless-stopped
    tty: true
    stdin_open: true
    hostname: mcl-${BOTS_DIR:-temp}
    volumes:
      # Public Files
      - ${MNT_DIR:-/mnt/docker}/mcl/libs:/app/libs
      - ${MNT_DIR:-/mnt/docker}/mcl/plugins:/app/plugins
      - ${MNT_DIR:-/mnt/docker}/mcl/plugin-libraries:/app/plugin-libraries
      - ${MNT_DIR:-/mnt/docker}/mcl/ANDROID_PAD.json:/app/android_pad.json
      - ${MNT_DIR:-/mnt/docker}/mcl/KFCFactory.json:/app/KFCFactory.json
      - ${MNT_DIR:-/mnt/docker}/mcl/mcl:/app/mcl
      # Bots Files
      - ${MNT_DIR:-/mnt/docker}/mcl/configs/${BOTS_DIR:-temp}/bots:/app/bots
      - ${MNT_DIR:-/mnt/docker}/mcl/configs/${BOTS_DIR:-temp}/config/Console/AutoLogin.yml:/app/config/Console/AutoLogin.yml
      - ${MNT_DIR:-/mnt/docker}/mcl/configs/${BOTS_DIR:-temp}/config/net.mamoe.mirai-api-http/setting.yml:/app/config/net.mamoe.mirai-api-http/setting.yml
      - ${TMP_DIR:-/tmp}/mcl/configs/${BOTS_DIR:-temp}/logs:/app/logs
    ports:
      - ${PORT}:8080
    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
    networks:
      - web

networks:
  web:
    external: true
