services:
  certimate:
    image: certimate/certimate:${IMAGE_TAG:-v0.4}
    container_name: ${CONTAINER_NAME:-certimate}
    restart: unless-stopped

    ports:
      - ${PORT:-8090}:8090

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/certimate:/app/pb_data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    extra_hosts:
      - host.docker.internal:host-gateway
