services:
  shlink:
    image: shlinkio/shlink:${SHLINK_IMAGE_TAG:-stable}
    # container_name: ${SHLINK_CONTAINER_NAME:-shlink}

    restart: unless-stopped

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${SHLINK_HOST_PORT:-8080}:8080"

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN:?DEFAULT_DOMAIN is required}
      IS_HTTPS_ENABLED: ${IS_HTTPS_ENABLED:-true}
      DB_DRIVER: ${DB_DRIVER:-mysql}
      DB_NAME: ${DB_NAME:-shlink}
      DB_USER: ${DB_USER:-shlink}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      DB_HOST: ${DB_HOST:-shlink_db}

    labels:
      com.centurylinklabs.watchtower.enable: ${SHLINK_WATCHTOWER_ENABLE:-true}
