services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:${IMAGE_TAG:-1.27.2}
    network_mode: host
    privileged: true
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    volumes:
      - ${MNT_DIR:-/mnt/docker}/nginx/html:/usr/share/nginx/html
      - ${MNT_DIR:-/mnt/docker}/nginx/logs:/var/log/nginx
      # etc
      - ${MNT_DIR:-/mnt/docker}/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ${MNT_DIR:-/mnt/docker}/nginx/conf.d:/etc/nginx/conf.d
      - ${MNT_DIR:-/mnt/docker}/nginx/template:/etc/nginx/template
      - ${MNT_DIR:-/mnt/docker}/nginx/cert:/etc/nginx/cert
