version: '3'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.25.5
    network_mode: host
    volumes:
      - ${MNT_DIR}/nginx/html:/usr/share/nginx/html
      - ${MNT_DIR}/nginx/www:/var/www
      - ${MNT_DIR}/nginx/logs:/var/log/nginx
      # etc
      - ${MNT_DIR}/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ${MNT_DIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${MNT_DIR}/nginx/templates:/etc/nginx/templates
      - ${MNT_DIR}/nginx/template:/etc/nginx/template
      - ${MNT_DIR}/nginx/cert:/etc/nginx/cert
    environment:
      - TZ=Asia/Shanghai
    privileged: true