services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:${IMAGE_TAG:-1.27.2}
    network_mode: host
    privileged: true
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    volumes:
      - ${HTML_DIR:-nginx_html}:/usr/share/nginx/html
      - ${LOGS_DIR:-nginx_logs}:/var/log/nginx
      # etc
      - ${NGINX_DIR:-/mnt/docker}/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ${CONF_DIR:-/mnt/docker}/nginx/conf.d:/etc/nginx/conf.d
      - ${TEMPLATE_DIR:-/mnt/docker}/nginx/template:/etc/nginx/template
      - ${CERT_DIR:-/mnt/docker}/nginx/cert:/etc/nginx/cert

volumes:
  nginx_logs:
  nginx_html:
