services:
  portainer-ce:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      - ${MNT_DIR:-/mnt/docker}:${MNT_DIR:-/mnt/docker}
    ports:
      - 9000:9000
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${HOST:-portainer.localhost}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - web

volumes:
  portainer:

networks:
  web:
    external: true
