services:
  portainer-ce:
    image: portainer/portainer-ce:${IMAGE_TAG:-alpine}
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      - ${MNT_DIR:-/mnt/docker}:${MNT_DIR:-/mnt/docker}
    ports:
      - ${PORT:-9000}:9000
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true} # watchtower
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    networks:
      - web

networks:
  web:
    external: true
