services:
  portainer-ce:
    image: portainer/portainer-ce:${IMAGE_TAG:-alpine}
    container_name: portainer
    restart: unless-stopped

    ports:
      - ${PORT:-9000}:9000

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s

    volumes:
      - portainer:/data
      - ${MNT_DIR:-/mnt/docker}:${MNT_DIR:-/mnt/docker}
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  portainer:
