version: '3'
services:
  portainer-ce:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data:/data
    ports:
      - 9000:9000
      - 9443:9443