services:
  mysql-bkup:
    image: jkaninda/mysql-bkup:${IMAGE_TAG:-latest}
    # container_name: ${CONTAINER_NAME:-mysql-bkup}

    restart: unless-stopped
    command: backup --all-databases

    networks:
      - web
    extra_hosts:
      - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      BACKUP_CRON_EXPRESSION: ${BACKUP_CRON_EXPRESSION:-@daily}
      BACKUP_RETENTION_DAYS: ${BACKUP_RETENTION_DAYS:-1}
    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true} # watchtower

    volumes:
      - ${MNT_DIR:-/mnt/docker}/mysql-bkup:/backup
networks:
  web:
    external: true
