services:
  mysql-client: 
    image: arey/mysql-client:${IMAGE_TAG:-latest}
    container_name: mysql-client
    volumes:
      - /tmp/mysql-client:/tmp
      - /home/ecs-user/run.sh:/run.sh
    entrypoint: ["/bin/ash", "-c"]
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true} # watchtower
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    command:
      - |
        while true; do
          echo $(date +'%H:%M')
          if [ "$(date +'%H:%M')" = '21:30' ]; then
            cd /
            ./run.sh
          elif [ "$(date +'%H:%M')" = '08:30' ]; then
            cd /
            ./run.sh
          fi
          sleep 60
        done
