services:
  mihomo:
    image: metacubex/mihomo:${IMAGE_TAG:-latest}

    restart: always

    network_mode: host

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
      - mihomo:/root/.config/mihomo
      - ${MNT_DIR:-.}/config.yaml:/root/.config/mihomo/config.yaml

    cap_add:
      - ALL

    security_opt:
      - apparmor=unconfined

    pid: host
    ipc: host

volumes:
  mihomo:
