services:
  mihomo:
    image: metacubex/mihomo:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-mihomo}

    restart: always

    network_mode: host

    # extra_hosts:
    #   - host.docker.internal:host-gateway

    env_file:
      - path: .env
        required: false

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
      - mihomo:/root/.config/mihomo
      - ${MNT_DIR:-/mnt/docker}/mihomo/config.yaml:/root/.config/mihomo/config.yaml

    cap_add:
      - ALL

    security_opt:
      - apparmor=unconfined

    pid: host
    ipc: host

volumes:
  mihomo:
