services:
  mihomo:
    container_name: mihomo
    image: metacubex/mihomo:v1.18.9
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
      - ${MNT_DIR:-/mnt/docker}/mihomo:/root/.config/mihomo

  metacubexd:
    container_name: metacubexd-ui
    image: mrxianyu/metacubexd-ui:latest
    restart: always
    ports:
      - '${PORT}:80'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.mihomo.rule=Host(`${HOST:-mihomo.localhost}`)
    networks:
      - web

networks:
  web:
    external: true
