services:
  mihomo:
    container_name: mihomo
    image: metacubex/mihomo:v1.18.9
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
      - ${MNT_DIR:-/mnt/docker}/mihomo:/root/.config/mihomo

