services:
  napcat-message-archiver-worker:
    image: sliots/napcat-message-archiver-worker:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-napcat-message-archiver-worker}
    hostname: ${HOSTNAME:-napcat-message-archiver-worker}
    restart: unless-stopped

    extra_hosts:
      - host.docker.internal:host-gateway

    environment:
      TZ: ${TZ:-Asia/Shanghai}

      # 数据库
      POSTGRES_HOST: ${POSTGRES_HOST:-172.17.0.1}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # WORKER_CNGAL
      WORKER_CNGAL_NAPCAT_API_URL: ${WORKER_CNGAL_NAPCAT_API_URL}
      WORKER_CNGAL_NAPCAT_AUTH_TOKEN: ${WORKER_CNGAL_NAPCAT_AUTH_TOKEN}
      WORKER_CNGAL_SELF_ID: ${WORKER_CNGAL_SELF_ID}
      WORKER_CNGAL_GROUP_IDS: ${WORKER_CNGAL_GROUP_IDS}
      WORKER_CNGAL_REFRESH_INTERVAL: ${WORKER_CNGAL_REFRESH_INTERVAL:-3600}
      WORKER_CNGAL_MIN_MATCH_LENGTH: ${WORKER_CNGAL_MIN_MATCH_LENGTH:-2}
      WORKER_CNGAL_NO_MATCH_ACTION: ${WORKER_CNGAL_NO_MATCH_ACTION:-skip}
      WORKER_CNGAL_IGNORE_USER_IDS: ${WORKER_CNGAL_IGNORE_USER_IDS}
      WORKER_CNGAL_BLACKLIST: ${WORKER_CNGAL_BLACKLIST}
      WORKER_CNGAL_REJECT_REASON: ${WORKER_CNGAL_REJECT_REASON}
      WORKER_CNGAL_WELCOME_TEXT: ${WORKER_CNGAL_WELCOME_TEXT}
      WORKER_CNGAL_FEISHU_WEBHOOK_URL: ${WORKER_CNGAL_FEISHU_WEBHOOK_URL}
      WORKER_CNGAL_FEISHU_TEMPLATE_ID: ${WORKER_CNGAL_FEISHU_TEMPLATE_ID}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}
