services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    restart: always
    environment: 
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock