services:
  autoheal:
    image: willfarrell/autoheal:${IMAGE_TAG:-1.2.0}
    container_name: ${CONTAINER_NAME:-autoheal}
    restart: unless-stopped

    environment:
      TZ: ${TZ:-Asia/Shanghai}
      AUTOHEAL_CONTAINER_LABEL: ${AUTOHEAL_CONTAINER_LABEL:-all}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
