services:
  kikoeru:
    image: number17/kikoeru:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-kikoeru}

    restart: unless-stopped

    networks:
      - web

    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT:-12345}:8888"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

    environment:
      TZ: ${TZ:-Asia/Shanghai}
    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${MNT_DIR:-/mnt/docker}/kikoeru/sqlite:/usr/src/kikoeru/sqlite
      - ${MNT_DIR:-/mnt/docker}/kikoeru/covers:/usr/src/kikoeru/covers
      - ${MNT_DIR:-/mnt/docker}/kikoeru/config:/usr/src/kikoeru/config
      - ${DATA_DIR:?DATA_DIR is required}:/usr/src/kikoeru/VoiceWork

networks:
  web:
    external: true
